name: Deploy Django Backend

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact (source code only)
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: |
            .
            !antenv/
            !**/__pycache__/
            !output.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: django-app

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: "NOVYA-BACKEND-DJANGO"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
